export default {
  extends: ['stylelint-config-standard', 'stylelint-config-clean-order'],
  overrides: [
    {
      files: ['**/*.{js,jsx,ts,tsx}'],
      customSyntax: 'postcss-styled-syntax',
    },
  ],
  rules: {
    'no-empty-source': null,
    'order/properties-order': [
      [
        {
          groupName: 'layout',
          emptyLineBefore: 'always',
          properties: [
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'display',
            'flex',
            'flex-direction',
            'flex-wrap',
            'flex-flow',
            'flex-basis',
            'flex-shrink',
            'flex-grow',
            'justify-content',
            'align-items',
            'align-content',
            'align-self',
            'order',
            'gap',
            'row-gap',
            'column-gap',
            'place-content',
            'place-items',
            'place-self',
            'grid',
            'grid-template',
            'grid-template-columns',
            'grid-template-rows',
            'grid-template-areas',
            'grid-area',
            'grid-auto-flow',
            'grid-auto-rows',
            'grid-auto-columns',
            'grid-column',
            'grid-row',
            'grid-column-start',
            'grid-column-end',
            'grid-row-start',
            'grid-row-end',
            'visibility',
            'overflow',
            'float',
            'clear',
            'position',
            'top',
            'right',
            'bottom',
            'left',
            'z-index',
          ],
        },

        {
          groupName: 'box',
          emptyLineBefore: 'always',
          properties: [
            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
            'border',
            'border-width',
            'border-style',
            'border-color',
            'box-sizing',
          ],
        },
        {
          groupName: 'background',
          emptyLineBefore: 'always',
          properties: [
            'background',
            'background-color',
            'background-image',
            'background-size',
            'background-position',
            'background-repeat',
            'background-blend-mode',
            'background-clip',
            'background-origin',
            'background-attachment',
          ],
        },
        {
          groupName: 'font',
          emptyLineBefore: 'always',
          properties: [
            'color',
            'font',
            'font-size',
            'font-weight',
            'font-family',
            'font-style',
            'font-variant',
            'font-feature-settings',
            'font-kerning',
            'font-stretch',
            'font-size-adjust',
            'font-smoothing',
            'font-synthesis',
            'font-variant-caps',
            'font-variant-ligatures',
            'letter-spacing',
            'text-align',
            'text-decoration',
            'text-decoration-color',
            'text-decoration-line',
            'text-decoration-style',
            'text-indent',
            'text-transform',
            'vertical-align',
            'white-space',
          ],
        },
        {
          groupName: 'animation',
          emptyLineBefore: 'always',
          properties: [
            'transition',
            'transition-delay',
            'transition-duration',
            'transition-property',
            'transition-timing-function',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-play-state',
            'animation-timing-function',
            'animation-delay',
            'animation-iteration-count',
            'animation-direction',
            'animation-fill-mode',
          ],
        },
        {
          groupName: 'etc',
          emptyLineBefore: 'always',
          properties: [],
        },
      ],
      { unspecified: 'bottomAlphabetical' },
    ],
    'no-descending-specificity': null,
  },
};
