############################################
# 1️⃣ Build Stage
############################################
FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle settings.gradle ./

RUN chmod +x gradlew

RUN ./gradlew dependencies --no-daemon

COPY src src

RUN ./gradlew clean build -x test --no-daemon

############################################
# 2️⃣ Runtime Stage
############################################
FROM eclipse-temurin:21-jre

WORKDIR /app

RUN mkdir -p /logs/dumps && chmod -R 777 /logs

COPY --from=builder /app/build/libs/*.jar app.jar

EXPOSE 8080

ENV JAVA_OPTS="-XX:InitialRAMPercentage=70.0 \
           -XX:MaxRAMPercentage=70.0 \
           -XX:MetaspaceSize=128M \
           -XX:MaxMetaspaceSize=256M \
           -XX:+UseG1GC \
           -XX:+UseContainerSupport \
           -XX:+HeapDumpOnOutOfMemoryError \
           -XX:HeapDumpPath=/logs/dumps/heapdump.hprof \
           -XX:ErrorFile=/logs/hs_err_pid%p.log \
           -Xlog:gc=info:file=/logs/gc.log:time,uptime:filecount=3,filesize=5M"

ENTRYPOINT ["sh", "-c", "java ${JAVA_OPTS} -Dspring.profiles.active=${SPRING_ACTIVE_PROFILE:-dev} -jar /app/app.jar"]
