version: '3.8'
services:
  backend-blue:
    image: pickeat/pickeat:release
    container_name: backend-blue
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./data/springboot/logs/blue:/var/logs
    environment:
      SPRING_ACTIVE_PROFILE: prod
    networks:
      - app-tier

  backend-green:
    image: pickeat/pickeat:release
    container_name: backend-green
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./data/springboot/logs/green:/var/logs
    environment:
      SPRING_ACTIVE_PROFILE: prod
    networks:
      - app-tier

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ./data/springboot/logs/blue:/var/log/spring/blue
      - ./data/springboot/logs/green:/var/log/spring/green
      - ./data/alloy/config.alloy:/etc/alloy/config.alloy
    environment:
      - ALLOY_ENV=prod
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
