version: '3.8'

x-common-env: &common-env
  SPRING_ACTIVE_PROFILE: dev
  OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317
  OTEL_RESOURCE_ATTRIBUTES: "environment=dev"

services:
  backend-blue:
    image: pickeat/pickeat:latest
    container_name: backend-blue
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - ./config/otel.env
    volumes:
      - ./data/springboot/logs/blue:/var/logs
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: pickeat-backend-blue
    depends_on:
      - mysqldb
    networks:
      - app-tier

  backend-green:
    image: pickeat/pickeat:latest
    container_name: backend-green
    restart: unless-stopped
    ports:
      - "8081:8080"
    env_file:
      - ./config/otel.env
    volumes:
      - ./data/springboot/logs/blue:/var/logs
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: pickeat-backend-green

    depends_on:
      - mysqldb
    networks:
      - app-tier

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pickeat_db
      MYSQL_USER: pickeat
      MYSQL_PASSWORD: pickeatcheeze33
      SPRING_ACTIVE_PROFILE: dev
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - 'mysqldb-data:/var/lib/mysql'
    networks:
      - app-tier

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    ports:
      - "12345:12345"
      - "5317:4317"
    volumes:
      - ./data/springboot/logs/blue:/var/log/spring/blue
      - ./data/springboot/logs/green:/var/log/spring/green
      - ../proxy/nginx/logs:/var/log/nginx
      - ./data/alloy/config.alloy:/etc/alloy/config.alloy
      - ./data/alloy/state:/var/lib/alloy
    environment:
      - ALLOY_ENV=dev
      - TZ=Asia/Seoul
      - TEMPO_ENDPOINT=10.0.1.28:4317
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    networks:
      - app-tier

volumes:
  mysqldb-data:
    driver: local

networks:
  app-tier:
    driver: bridge
    name: docker_app-tier
