version: '3.8'
services:
  backend:
    image: pickeat/pickeat:release
    environment:
      SPRING_ACTIVE_PROFILE: prod
    restart: always
    ports:
      - "80:8080"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
