version: '3.8'

x-common-env: &common-env
  SPRING_ACTIVE_PROFILE: local
  OTEL_SERVICE_VERSION: latest
  OTEL_EXPORTER_OTLP_ENDPOINT: http://alloy:4317

services:
  backend-blue:
    build: ../
    container_name: backend-blue
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./config/otel.env
    volumes:
      - ./data/springboot/logs/blue:/var/logs
    environment:
      <<: *common-env
      OTEL_SERVICE_NAME: pickeat-backend-blue
      OTEL_RESOURCE_ATTRIBUTES: "environment=local,deployment=blue,service=pickeat"
    depends_on:
      - mysqldb
      - alloy
    networks:
      - app-tier

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pickeat_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - 'mysqldb-data:/var/lib/mysql'
    networks:
      - app-tier

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    ports:
      - "12345:12345"
      - "5317:4317"
    volumes:
      - ./data/springboot/logs/blue:/var/log/spring/blue:ro
      - ./data/springboot/logs/green:/var/log/spring/green:ro
      - ../proxy/nginx/logs:/var/log/nginx:ro
      - ./data/alloy/config.alloy:/etc/alloy/config.alloy:ro
    environment:
      - ALLOY_ENV=dev
      - TZ=Asia/Seoul
      - TEMPO_ENDPOINT=tempo:4317
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    networks:
      - app-tier
      - monitor-tier

volumes:
  mysqldb-data:
    driver: local

networks:
  app-tier:
    driver: bridge
    name: docker_app-tier
  monitor-tier:
    external: true
    name: docker_monitor-tier
