name: CI Check Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci-check:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write
      pull-requests: write
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SUBMODULE_KEY }}
          submodules: true

      - name: Update Submodule
        run: git submodule update --remote

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Check Test Success
        run: ./gradlew test
        working-directory: ./backend

      - name: Check Gradle Build Success
        run: ./gradlew build -x test
        working-directory: ./backend

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            backend/build/test-results/**/*.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
